### PR TITLE
added battery unit (for Home Assistant

### PR DESCRIPTION
**Pull request by rico0260**
For Home Assistant you absolutely need unity otherwise there is no curve but a kind of horizontal bar.

image

image

### CODE REVIEW

**Comment by alexander-vitishchenko** [comment]
Hi @rico0260 

Let me look at it and merge the changes during weekend. 

Just fyi - need more time as I'm in progress with massive refactoring of the codebase + creating more automated regressions tests for CI/CD pipeline to further improve the quality of the future release and make sure new gestures do not break the existing functionality

**Comment by rico0260** [comment]
no problem, take your time.

**Comment by rico0260** [comment]
Here are some new changes because scenes are not devices and that is causing problems for me.

**Comment by alexander-vitishchenko** [comment]
Hi @rico0260 - I've implemented the "unit of measurement" for battery sensors, except units should be set while device "creation", not when distributed to MQTT, which is to keep the codebase closer to MVC principle and improve its maintainability

I'll publish the new QuickApp version tomorrow along with other changes accumulated over the last few weeks

**Comment by alexander-vitishchenko** [comment]
@rico0260 one open question based on the second part of your pull request

Do you still need and propose the QuickApp to process "SceneStartedEvent" and" SceneFinishedEvent"? 

It looks like you added more logging to the QuickApp/Fibaro HC3 side, without event sync to Home Assistant. Please advise what's the end goals, so I could see how to help

**Comment by alexander-vitishchenko** [comment]
Hi @rico0260 - battery level sensor got "unit of measurement" assigned

Is there anything else you'd like to implement? Please check my previous question above

**Comment by rico0260** [comment]
The problem I had on the previous version was an event that came from a Fibaro scenario with the same Id from another device and its display in the logs didn't seem very logical to me (the scenario event was very often present in my logs but not important to me).
Today the Fibaro scenario event no longer appears in the logs and that's better.
For me it is closed.
Thank you very much for the good work of this quickApp

**Pull request closed without merging**
